var wasmBase64 = "";
var WASM = {
	clearTopAndLeft:null,
	clearHROTOutside:null,
	wrapTorusHROT:null,
	nextGenerationHROTVN2:null,
	nextGenerationHROTVNN:null,
	nextGenerationHROTMoore2:null,
	nextGenerationHROTMooreN:null,
	cumulativeMooreCounts2:null,
	cumulativeMooreCountsN:null,
	cumulativeVNCounts2:null,
	cumulativeVNCountsN:null,
	updateOccupancyStrict:null,
	updateCellCounts:null,
	getHashTwoState:null,
	getHashSuper:null,
	getHashLifeHistory:null,
	getHashRuleLoaderOrPCAOrExtended:null,
	getHashGenerations:null,
	create2x2ColourGrid:null,
	create4x4ColourGrid:null,
	create8x8ColourGrid:null,
	create16x16ColourGrid:null,
	create32x32ColourGrid:null,
	create2x2ColourGridSuper:null,
	create4x4ColourGridSuper:null,
	create8x8ColourGridSuper:null,
	create16x16ColourGridSuper:null,
	create32x32ColourGridSuper:null,
	convertToPens:null,
	renderGridNoClipNoRotate:null,
	renderGridClipNoRotate:null,
	memory: null,
	allocator: null
};
