#! /bin/bash
# Build LifeViewer Javascript definition

echo "// LifeViewer WASM definitions"
echo "// This file is autogenerated during the build process"
echo ""
echo "var wasmBase64 = \"`cat $1`\";"
echo ""
echo "var WASM = {"
egrep "(^void|^uint32_t)" /mnt/c/Users/crowe/Documents/GitHub/lifeviewer/wasm/*.c | sed "s/.* /\t/" | sed "s/(/: null,/"
echo -e "\tmemory: null,\n\tallocator: null\n};"
